---
# Ansible Playbook installation script
- name: Install Longhorn
  hosts: workers
  become: true

  tasks:
    - name: Ensure Helm is installed
      ansible.builtin.command: helm version --short
      register: helm_check
      failed_when: helm_check.rc != 0
      changed_when: false

    - name: Add Longhorn Helm repository
      community.kubernetes.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
    
    - name: Install Longhorn via Helm
      community.kubernetes.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        wait: true
    
